global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['producer:8080']
        labels:
          service: 'log-producer'

  - job_name: 'processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['processor:8081']
        labels:
          service: 'log-processor'

